version: '2'
services:
    mpgsite-app:
        image: mpgsite
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://mpgsite-postgresql:5432/mpgsite
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mpgsite-postgresql:
        extends:
            file: postgresql.yml
            service: mpgsite-postgresql
